apiVersion: v1
kind: Service
metadata:
  name: {{ template "fluentd.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "fluentd.name" . }}
    chart: {{ template "fluentd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $port := .Values.service.ports }}
    - name: {{ $port.protocol | lower }}-{{ $port.name }}
      port: {{ $port.containerPort }}
      targetPort: {{ $port.containerPort }}
      protocol: {{ $port.protocol }}
  {{- end }}
  {{ if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
  {{ end }}
  {{- if .Values.metrics.enabled }}
    - name: tcp-metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "fluentd.name" . }}
    release: {{ .Release.Name }}
