apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    "helm.sh/hook": "post-install"
  labels:
    app.kubernetes.io/component: controller
    app: prometheus-operator
    app.kubernetes.io/version: v0.31.1
  name: prometheus-operator
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app: prometheus-operator
      app.kubernetes.io/version: v0.31.1
