# Configuration for running Cortex in single-process mode.
# This should not be used in production.  It is only for getting started
# and development.

image:
  repository: quay.io/cortexproject/cortex
  tag: v1.5.0
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name:
  annotations: {}

rbac:
  create: true
  pspEnabled: true

replicas: 1

cortexConfig:
  # Disable the requirement that every request to Cortex has a
  # X-Scope-OrgID header. `fake` will be substituted in instead.
  auth_enabled: false

  server:
    http_listen_port: 9009

    # Configure the server to allow messages up to 100MB.
    grpc_server_max_recv_msg_size: 104857600
    grpc_server_max_send_msg_size: 104857600
    grpc_server_max_concurrent_streams: 1000

  distributor:
    shard_by_all_labels: true
    pool:
      health_check_ingesters: true

  ingester_client:
    grpc_client_config:
      # Configure the client to allow messages up to 100MB.
      max_recv_msg_size: 104857600
      max_send_msg_size: 104857600
      grpc_compression: gzip

  limits:
    max_series_per_metric: 0
    max_series_per_user: 0
    max_metadata_per_user: 0
    max_metadata_per_metric: 100

  ingester:
    lifecycler:
      # The address to advertise for this ingester. Will be autodiscovered by
      # looking up address on eth0 or en0; can be specified if this fails.
      address: 0.0.0.0

      # We want to start immediately and flush on shutdown.
      join_after: 0
      final_sleep: 0s
      num_tokens: 512

      # Use an in memory ring store, so we don't need to launch a Consul.
      ring:
        kvstore:
          store: etcd
          etcd:
            endpoints:
              - neon-metrics-etcd:2379
        replication_factor: 1

  # Use yugabyte as storage -for both index store and chunks store.
  schema:
    configs:
    - from: 2019-07-29
      store: cassandra
      object_store: cassandra
      schema: v10
      index:
        prefix: index_
        period: 24h
      chunks:
        prefix: chunk_
        period: 24h

  storage:
    boltdb:
      directory: /tmp/cortex/index
    filesystem:
      directory: /tmp/cortex/chunks
    delete_store:
      store: boltdb
    cassandra:
      addresses: neon-metrics-db-yb-tservers # configure yugabyte addresses here.
      keyspace: cortex   # configure desired keyspace here.
      timeout: 15s
      connect_timeout: 15s
      max_retries: 5

  table_manager:
    retention_deletes_enabled: true
    retention_period: 48h



strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1

annotations: {}
nodeSelector:
  neonkube.io/monitor.metrics: 'true'

affinity: {}

tolerations:
  - key: "neonkube.io/metrics"
    operator: Exists
    effect: NoSchedule

resources:
  limits:
    cpu: 750m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "http-metrics"
  readiness.status.sidecar.istio.io/applicationPorts: '9009'

podLabels: {}

terminationGracePeriodSeconds: 2400

extraVolumes: {}

env: []

securityContext: {}

initContainers: []

startupProbe:
  exec:
    command:
    - "wget"
    - "-q"
    - "--spider"
    - "http://localhost:9009/ready"
  failureThreshold: 30
  periodSeconds: 10

livenessProbe:
  exec:
    command:
    - "wget"
    - "-q"
    - "--spider"
    - "http://localhost:9009/ready"
  initialDelaySeconds: 45
  periodSeconds: 3
readinessProbe:
  exec:
    command:
    - "wget"
    - "-q"
    - "--spider"
    - "http://localhost:9009/ready"
  initialDelaySeconds: 45
  periodSeconds: 3