---
# Source: m3db-operator/templates/cluster_role_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: m3db-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: m3db-operator
subjects:
- kind: ServiceAccount
  name: m3db-operator
  namespace: default